### PR TITLE
Use orb and add daily workflow

### PR DESCRIPTION
**Pull request by hhtong**

### CODE REVIEW

**Comment by JoelPasvolsky** [comment]
Do we want to run this daily? It takes about 10 minutes.

**Comment by hhtong** [comment]
I don't have a particular preference on this. Any thoughts? @randomir @arcondello

**Comment by arcondello** [comment]
Agree for these longer ones it might make sense to run it less frequently.

**Comment by randomir** [comment]
Assuming majority of that 10m is just a local compute (dwave-hybrid), so relatively cheap, I'd keep the daily runs.

If we want to optimize cost, let's just run the _latest python on all platforms daily_, and run the whole suite weekly (or something like that).

**Comment by hhtong** [comment]
Running only the latest python isn't something we can do with the current orb implementation, though it's a feature we can definitely add. For now, I'd be okay with just running these notebook tests weekly (all python versions, all platforms).

**Pull request merged**
